version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - 'angular-eslint'
          - 'ng-packagr'
      vitest:
        patterns:
          - '@vitest/*'
          - 'vitest'
      dev-dependencies:
        dependency-type: development
        update-types: [minor, patch]
      production-dependencies:
        dependency-type: production
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
